[package]
name = "procsps-rust"
version = "0.1.0"
authors = ["Joel Hermanns <joel.hermanns@gmail.com>"]

[dependencies]
libc = "0.1.8"
getopts = "0.2"
time = "0.1"

[[bin]]
name = "uptime"
path = "src/uptime.rs"
